export const TOGGLEDARKMODE = "TOGGLEDARKMODE";
export const STATISTICS = "STATISTICS";
export const CHANGE_WALLET = "CHANGE_WALLET";
export const LOCKERSDATA = "LOCKERSDATA";
export const LOCKERDATA = "LOCKERDATA";
export const TOKENDATA = "TOKENDATA";
export const USERBALANCE = "USERBALANCE";
export const TOKENLISTS = 'TOKENLISTS';